apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diegopm-dev
  name: diegopm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diegopm-dev
  strategy: {}
  template:
    metadata:
      labels:
        app: diegopm-dev
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/diegopm-dev/app:latest
        name: diegopm-dev
        ports:
        - containerPort: 8080
        resources: {}
