apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: pida-diego
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pida-diego/app:d5c985c4-dad4-4a7b-8c38-720a0403ec44
          name: app
          ports:
          - containerPort: 8080
          resources: {}
