apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: pida-diego
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pida-diego/app:f9da1234-12ae-4e3f-bfd1-1c5be4b0bad7
          name: app
          ports:
          - containerPort: 8080
          resources: {}
