apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: pida-diego
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pida-diego/app:451df296-0425-4eb8-a1e0-e9f91bfa8df6
          name: app
          ports:
          - containerPort: 8080
          resources: {}
