apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: image
    newName: image-registry.openshift-image-registry.svc:5000/pida-diego/app
    newTag: 7fdd786b-5248-4465-a082-311bac84fc18
