apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
images:
  - name: image
    newName: image-registry.openshift-image-registry.svc:5000/pida-diego/app
    newTag: 7e0126ba-4a80-41ef-8a5f-0348c61a32f6
