apiVersion: v1
kind: Service
metadata:
  labels:
    app: diegopm-dev
  name: diegopm-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: diegopm-dev
  type: ClusterIP
