apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pida-diego
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'git@github.com:diegomacielp/tekton-pipeline.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true