apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pida-diego
  namespace: openshift-gitops-operator
spec:
  destination:
    name: ''
    namespace: openshift-gitops-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: tmp
    repoURL: 'https://github.com/diegomacielp/tekton-pipeline.git'
    targetRevision: main
  project: default
