apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline
  podTemplate:
    securityContext:
      fsGroup: 65332
  params:
    - name: repo-url
      value: 'git@github.com:diegomacielp/tekton-pipeline.git'
    - name: revision
      value: main
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-credentials
      secret:
        secretName: git-credentials
        #- name: varlibcontainers
        #emptyDir: {}
