apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
    - name: PROJECT
      type: string
    - name: APPLICATION
      type: string
  workspaces:
    - name: workspace
    - name: git-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: workspace
        - name: ssh-directory
          workspace: git-credentials
    - name: image-build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: image-build-push
      params:
        - name: PROJECT
          value: $(params.PROJECT)
        - name: APPLICATION
          value: $(params.APPLICATION)
      workspaces:
        - name: source
          workspace: workspace
