apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun
spec:
  pipelineRef:
    name: pipeline
  #podTemplate:
  #  securityContext:
  #    fsGroup: 65532
  params:
    - name: repo-url
      value: 'https://github.com/diegomacielp/tekton-pipeline.git'
    - name: revision
      value: main
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-creds
      secret:
        secretName: ssh-credential
    - name: varlibcontainers
      emptyDir: {}
