apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
  workspaces:
    - name: workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: workspace
    #- name: build-app
    #  runAfter: ["fetch-source"]
    #  taskRef:
    #    name: build-app
    #  workspaces:
    #    - name: source
    #      workspace: workspace
    - name: build-image
      runAfter: ["fetch-source"]
      taskRef:
        name: build-image
      workspaces:
        - name: source
          workspace: workspace