apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline
  params:
    - name: repo-url
      value: 'git@github.com:diegomacielp/tekton-pipeline.git'
    - name: revision
      value: main
    - name: PROJECT
      value: pida-diego
    - name: APPLICATION
      value: app
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    - name: git-credentials
      secret:
        secretName: git-credentials
    - name: varlibcontainers
      emptyDir: {}
