apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy
spec:
  params:
    - name: TLSVERIFY
      type: string
      default: "false"  
  steps:
    - name: npm-install
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm install
      workingDir: /workspace/app
    - name: npm-test
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run test
      workingDir: /workspace/app
    - name: npm-build
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: /workspace/app