apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: striggertemplate
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      default: main
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: simple-pipeline-run
      spec:
        pipelineRef:
          name: pipeline
        params:
          - name: url
            value: $(tt.params.repo-url)
          - name: revision
            value: $(tt.params.revision)